# docker-compose.yml
version: '2'

services:
  api:
    build:
      # build from Dockerfile
      context: ./
      dockerfile: Dockerfile
    image: habittracker
    container_name: habittracker
    ports: 
      - 4040:4040